name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Update CocoaPods repo
        run: pod repo update
        working-directory: ios

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Create Payload directory
        run: mkdir -p Payload
        working-directory: build/ios/iphoneos

      - name: Move app to Payload directory
        run: mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      - name: Zip the Payload directory
        run: zip -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0
          release_name: 'v1.0'
          body: "This is the first release."
          draft: false
          prerelease: false

      - name: Upload IPA to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/ios/iphoneos/FlutterIpaExport.ipa
          asset_name: FlutterIpaExport.ipa
          asset_content_type: application/octet-stream
